export const dummy = {
  dates: { maximum: "2022-08-28", minimum: "2022-07-11" },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/xfNHRI2f5kHGvogxLd0C5sB90L7.jpg",
      genre_ids: [16, 28, 10751, 878, 35],
      id: 539681,
      original_language: "en",
      original_title: "DC League of Super-Pets",
      overview:
        "악당 렉스 루터의 계략으로 위험에 빠진 슈퍼맨을 비롯한 저스티스 리그의 슈퍼 히어로들을 구하기 위해 슈퍼독 크립토와 슈퍼 펫 친구들이 벌이는 파워 댕댕 모험을 그린 이야기",
      popularity: 4630.031,
      poster_path: "/4L7hgezinra0QudLN8HPv8c3af1.jpg",
      release_date: "2022-08-10",
      title: "DC 리그 오브 슈퍼-펫",
      video: false,
      vote_average: 7.6,
      vote_count: 243,
    },
    {
      adult: false,
      backdrop_path: "/lbLPVvgq16BD3IA6sIH3riu9ouO.jpg",
      genre_ids: [27, 9648, 878, 53],
      id: 762504,
      original_language: "en",
      original_title: "Nope",
      overview:
        "거대하고, 주목받길 원하고, 미쳤다. 나쁜 기적이라는 것도 있을까?",
      popularity: 1986.873,
      poster_path: "/52McjY2vAEiF0lJe8iBdOBNuyok.jpg",
      release_date: "2022-08-17",
      title: "놉",
      video: false,
      vote_average: 7.1,
      vote_count: 835,
    },
    {
      adult: false,
      backdrop_path: "/27Mj3rFYP3xqFy7lnz17vEd8Ms.jpg",
      genre_ids: [28, 53],
      id: 725201,
      original_language: "en",
      original_title: "The Gray Man",
      overview:
        "그 누구도 실체를 몰라 그레이 맨으로 불리는 CIA의 암살 전문 요원이우연히 CIA의 어두운 비밀을 발견한다. 이런 그의 목에 현상금을 건 소시오패스 기질의 전직 요원. 세계 곳곳을 배경으로 두 사람의 쫓고 쫓기는 추격전이 펼쳐진다.",
      popularity: 1092.295,
      poster_path: "/3weHvdbJ9RiSNHS0cz5694fkAnk.jpg",
      release_date: "2022-07-13",
      title: "그레이 맨",
      video: false,
      vote_average: 7,
      vote_count: 1848,
    },
    {
      adult: false,
      backdrop_path: "/C8FpZfTPEZDjngPlatiFsaDB4A.jpg",
      genre_ids: [28, 35, 80],
      id: 718930,
      original_language: "en",
      original_title: "Bullet Train",
      overview:
        "운이 없기로 유명한 킬러 레이디버그는 초고속 열차에 탑승해 의문의 서류 가방을 가져오라는 미션을 받는다. 생각보다 쉽게 미션을 클리어한 후 열차에서 내리려는 그를 가로막는 것이 있었으니,  그것은 바로 전세계에서 몰려든 초특급 킬러들! 열차에서 내릴 수 없다면 목숨을 걸고 가방을 지켜야만 한다. 과연 레이디버그는 무사히 열차에서 내려 미션을 완수할 수 있을까?",
      popularity: 732.037,
      poster_path: "/msh4N8dxHk4FeEPZ8VBqHQFQYjI.jpg",
      release_date: "2022-08-24",
      title: "불릿 트레인",
      video: false,
      vote_average: 7.5,
      vote_count: 554,
    },
    {
      adult: false,
      backdrop_path: "/vjnLXptqdxnpNJer5fWgj2OIGhL.jpg",
      genre_ids: [28, 53, 80],
      id: 818397,
      original_language: "en",
      original_title: "Memory",
      overview:
        "단 한번의 실패도 실수도 용납할 수 없는 킬러 ‘알렉스’(리암 니슨). 어느 날, 그에게 새로운 의뢰가 들어온다.  오직 자신의 신념에 따라 움직인 그는 이 사건에 한 소녀가 연관되어 있음을 알게 되고 단칼에 거절한다.  의뢰를 거절했다는 이유로, 모두의 표적이 되어버린 그는 오래된 병으로 인해 희미해져 가는 기억을 붙잡고,  소녀와 자신을 지키기 위해 의뢰에 연관된 모든 것들을 응징하기로 한다.  한편, 멕시코 국경에서 사건을 맹렬히 쫓던 FBI 요원 ‘빈센트’(가이 피어스)는 ‘알렉스’를 만나게 되고, 두 사람은 이 사건의 거대한 비밀과 마주하게 되는데···  사라지는 기억, 더욱 선명해지는 정의! 마지막 응징이 시작된다!",
      popularity: 675.418,
      poster_path: "/fWkFnlCQLtfIBGnhMKVw2dttEDk.jpg",
      release_date: "2022-07-13",
      title: "메모리",
      video: false,
      vote_average: 7.3,
      vote_count: 725,
    },
    {
      adult: false,
      backdrop_path: "/A5OlbPn10H3E16CY8CT8fplWZy7.jpg",
      genre_ids: [80, 18, 53],
      id: 689700,
      original_language: "en",
      original_title: "Clean",
      overview:
        "폭력으로 얼룩진 어두운 과거를 청산하고 쓰레기차를 모는 청소부로 조용한 삶을 보내고 있는 클린.\r 주인 없는 개를 돌보고, 버려진 집을 보수하며 속죄하듯 거리를 청소하는 그에게는\r 할머니와 단둘이 사는 이웃 소녀 디안다만이 유일한 친구다.  한편, 마약을 유통하며 경찰까지 좌지우지하는 갱단 보스 마이클의 아들 마이키의 출소 기념 파티에서\r 위험에 처한 디안다를 목격한 클린은 마이키와 패거리들을 엉망으로 만들고 디안다를 구해내는 데 성공한다.  마이클과 경찰 모두에게 쫓기는 신세가 된 클린은\r 마이클의 조직이 끝내 자신들을 찾아낼 것을 누구보다 잘 알기에 홀로 마을로 되돌아오고,\r 베일에 싸여 있던 그의 진짜 과거를 알게 된 마이클 역시 클린과의 마지막 싸움을 준비하는데…!",
      popularity: 321.868,
      poster_path: "/gnWr71M3GhvVZs64UVMuvpdhHHb.jpg",
      release_date: "2022-08-25",
      title: "클린",
      video: false,
      vote_average: 6.6,
      vote_count: 202,
    },
    {
      adult: false,
      backdrop_path: "/2tVdN2eWsdTegTDuC0miHwGb31E.jpg",
      genre_ids: [18, 12, 53],
      id: 895953,
      original_language: "es",
      original_title: "La cima",
      overview:
        "가장 많은 목숨을 빼앗은 안나푸르나. 죽은 연인을 위해 나선 등반에서 사고를 당하는 남자. 더 이상 오를 곳이 없는 최고의 등반가에게 구조된다. 서로의 아픔과 무모한 도전을 이해하고 도와주려 하지만 남자는 성치 않은 몸으로 목숨을…",
      popularity: 113.142,
      poster_path: "/uEmZQXBVQljK93ma1xNwj8YMOAx.jpg",
      release_date: "2022-07-28",
      title: "안나푸르나: 비욘드 써밋",
      video: false,
      vote_average: 6,
      vote_count: 5,
    },
    {
      adult: false,
      backdrop_path: "/7ZP8HtgOIDaBs12krXgUIygqEsy.jpg",
      genre_ids: [28, 14, 9648, 878, 35],
      id: 601796,
      original_language: "ko",
      original_title: "외계+인 1부",
      overview:
        "2022년 현재, 가드와 썬더는 인간의 몸에 가두어진 외계인 죄수를 관리하며 지구에 살고 있다. 어느 날, 서울 상공에 우주선이 나타나고 형사 문도석은 기이한 광경을 목격하게 되는데.. 한편, 630년 전 고려시대 얼치기 도사 무륵과 천둥 쏘는 처자 이안이 엄청난 현상금이 걸린 신검을 차지하기 위해 서로를 속고 속이는 가운데 신검의 비밀을 찾는 두 신선 흑설과 청운, 가면 속의 자장도 신검 쟁탈전에 나선다. 그리고 우주선이 깊은 계곡에서 빛을 내며 떠오르는데…",
      popularity: 98.853,
      poster_path: "/i011PWRJcIVe8d9DscLagjRFuXd.jpg",
      release_date: "2022-07-20",
      title: "외계+인 1부",
      video: false,
      vote_average: 7.5,
      vote_count: 9,
    },
    {
      adult: false,
      backdrop_path: "/gSsTGqZ7wT0uGhLDpcUOe1jYsi6.jpg",
      genre_ids: [18, 80, 53],
      id: 660353,
      original_language: "en",
      original_title: "Ted K",
      overview:
        "산속 작은 오두막에 은둔 생활을 하고 있는, 세상을 등진 천재 수학자 ‘존 카진스키’\r 산업화와 산림개발 등으로 자신의 오두막이 파괴되고 생계를 위협받자\r 세상에 대한 증오가 극에 달하고 무정부주의에 눈을 뜨면서 산업사회에 복수를 결심한다.\r 사제 폭발물 제조법을 독학으로 익혀 여러 차례 시험을 거친 후 세상을 바꿀 테러를 계획하게 되는데…",
      popularity: 50.959,
      poster_path: "/ufGdX51Xi8X0QAS0I4vuvPjSnKx.jpg",
      release_date: "2022-08-11",
      title: "유나바머: 테드 K",
      video: false,
      vote_average: 5.7,
      vote_count: 50,
    },
    {
      adult: false,
      backdrop_path: "/3DgGjoMjd188LN4v24Kw7iClKbT.jpg",
      genre_ids: [18],
      id: 660120,
      original_language: "no",
      original_title: "Verdens verste menneske",
      overview:
        "의학을 공부하던 스물아홉 율리에는 자신이 진짜 원하는 걸 찾아 세상으로 나온다. 파티에서 만난 만화가 악셀과 사랑에 빠진 율리에, 하지만 삶의 다른 단계에서 만난 두 사람은 각자 다른 걸 원했고 조금씩 어긋난다. “내 삶에서 조연 역할을 하는 것 같아…” 율리에는 인생의 다음 챕터로 달려나간다.",
      popularity: 50.494,
      poster_path: "/dpK3tNUsGEmrkKcmwsDMRt24cXW.jpg",
      release_date: "2022-08-25",
      title: "사랑할 땐 누구나 최악이 된다",
      video: false,
      vote_average: 7.6,
      vote_count: 635,
    },
    {
      adult: false,
      backdrop_path: "/utUVo1wt3i4OdrQQS3I9QeegYsM.jpg",
      genre_ids: [27, 53, 14],
      id: 780609,
      original_language: "en",
      original_title: "Men",
      overview:
        "남편의 죽음 이후, 마음을 치유하기 위해 평화롭고 아름다운 영국 시골 마을을 찾은 '하퍼'  어느 순간부터 집 주변의 숲에서 온 정체 모를 누군가, 아니 '무언가'가 그를 따라다니기 시작한다. 공포에 질린 '하퍼'는 마을 사람들에게 도움을 청하려 하지만 경찰관, 신부, 바텐더, 심지어 어린 소년까지 그들 모두의 기묘한 공통점이 드러나는데…",
      popularity: 47.34,
      poster_path: "/m3jSZSOptX0wzgCdyIVfhsvlCcj.jpg",
      release_date: "2022-07-13",
      title: "멘",
      video: false,
      vote_average: 6.3,
      vote_count: 263,
    },
    {
      adult: false,
      backdrop_path: "/fILWktCfh0ZiKWjWwyXalWzSvKX.jpg",
      genre_ids: [18, 35, 10749],
      id: 758330,
      original_language: "en",
      original_title: "Good Luck to You, Leo Grande",
      overview:
        "단 한번도 섹스에 만족해 본 적 없는 인생 6*년차 낸시. 남편과 아이들이 떠나고, 은퇴 후 혼자 남은 그녀는 자신만의 은밀한 버킷리스트를 실행해보기로 결심한다  \"이끌리는 대로 다 잊고 당신만 생각해요” 외딴 호텔, 모든 게 자신 없는 '낸시' 앞에 젊고 매력적인 '리오 그랜드'가 나타나고, 처음 경험하는 퍼스널 서비스는 예상치 못한 해방감을 선사하는데...  올 여름, 뜨겁게 용감해지고 싶은 당신을 위한 굿 럭 무비!",
      popularity: 40.222,
      poster_path: "/1ywjWmLHWHKAyOHGw0A3tcQclH0.jpg",
      release_date: "2022-08-11",
      title: "굿 럭 투 유, 리오 그랜드",
      video: false,
      vote_average: 7,
      vote_count: 93,
    },
    {
      adult: false,
      backdrop_path: "/wgbch1xH2OezrMKnol8Ze9UghPT.jpg",
      genre_ids: [53, 9648, 878, 27],
      id: 792678,
      original_language: "ja",
      original_title: "CUBE 一度入ったら、最後",
      overview:
        "이유도 모른 채 텅 빈 정육면체의 공간에서 깨어난 사람들. 알 수 없는 규칙으로 움직이기 시작하는 방을 넘어 탈출하려 하지만 숨겨져 있던 함정에 의해 하나 둘 끔찍한 죽음을 맞이한다. 가까스로 살아남은 6명의 생존자,  살아남기 위해선 함정을 피할 수 있는 규칙을 찾아내야만 하는데…",
      popularity: 38.301,
      poster_path: "/5uQk54sok5La77YdxetG4kji2ZD.jpg",
      release_date: "2022-07-13",
      title: "큐브",
      video: false,
      vote_average: 4.7,
      vote_count: 31,
    },
    {
      adult: false,
      backdrop_path: "/he0XbwtxDiRnPERvboWMkvXFdAJ.jpg",
      genre_ids: [18, 53],
      id: 807196,
      original_language: "en",
      original_title: "Boiling Point",
      overview:
        "365일 중 가장 바쁜 크리스마스, 런던의 고급 레스토랑.  셰프 ‘앤디’는 사고 없이 음식과 직원, 손님 모두를 살펴야 한다.  쏟아지는 주문으로 정신없는 가운데  반갑지 않은 위생 관리관의 급습과  입맛 까다로운 평론가의 눈치까지 보게 되고,  여기에 상황을 아는지 모르는지 직원들은 서로 싸우기까지 한다.  도저히 통제되지 않는 현장에  ‘앤디’는 점점 끓어오르기 시작하는데…",
      popularity: 36.887,
      poster_path: "/reiVOBoIb4YObjxLpMB4qQbdYbA.jpg",
      release_date: "2022-08-04",
      title: "보일링 포인트",
      video: false,
      vote_average: 7.3,
      vote_count: 195,
    },
    {
      adult: false,
      backdrop_path: "/2XQPcgGMyw2qSssv3CsCaOP61l3.jpg",
      genre_ids: [53, 10749, 18, 9648],
      id: 721625,
      original_language: "en",
      original_title: "Songbird",
      overview:
        "감염병 스릴러 영화 송버드(Songbird)는 COVID-23 바이러스가 창궐하여 전 세계가 봉쇄된 지 4년이 지난 시점을 그리고 있습니다.  코비드-23이 전 세계를 휩쓴지 4년이 지난 시점에 수많은 사람들의 노력에도 불구하고 바이러스는 돌연변이를 일으키며 더 치명적으로 변해가고, 바이러스에 감염된 미국인들은 집에서 끌려나와 Q-Zones로 알려진 수용소에 강제 격리되는데 이 수용소에 들어가면 살아 돌아오기 힘듭니다.  자전거 택배 기사로 일하는 니코( KJ 아파)는 치명적인 병원체에 면역이지만 그의 연인 새라(소피아 카슨)는 병원체에 감염되어 수용소로 끌려갈 위기에 처하게 됩니다. 그러자 그는 불모지로 변한 로스앤젤레스 거리를 가로질러 전 세계를 휩쓴 팬데믹을 헤치고 그녀를 구하기 위한 모험을 감행합니다.",
      popularity: 32.055,
      poster_path: "/5jhrMIDfpeHECYGJzTXE4K8NQL1.jpg",
      release_date: "2022-08-17",
      title: "락다운 213주",
      video: false,
      vote_average: 6.2,
      vote_count: 562,
    },
    {
      adult: false,
      backdrop_path: "/ue7p1gBxBZeM9KNtwcUnBzdlRHk.jpg",
      genre_ids: [18],
      id: 554230,
      original_language: "en",
      original_title: "The Lost Daughter",
      overview:
        "그리스로 혼자 휴가를 떠난 대학 교수 레다는 딸을 가진 젊은 여자 니나를 보고 단번에 시선을 빼앗긴다. 매일 같은 해변에서 시간을 보내며 서로를 응시하던 두 사람, 갑자기 니나의 딸이 사라지고 레다는 옛 기억을 떠올린다.",
      popularity: 30.527,
      poster_path: "/zm3l0B3Fubgwpw7jRUnusjUxW2k.jpg",
      release_date: "2022-07-14",
      title: "로스트 도터",
      video: false,
      vote_average: 6.6,
      vote_count: 630,
    },
    {
      adult: false,
      backdrop_path: "/aRJjCgp4uVUkXhDw8NClesQXbt3.jpg",
      genre_ids: [53, 28],
      id: 727340,
      original_language: "ko",
      original_title: "헌트",
      overview:
        "북한 고위 관리가 망명을 요청한 이후, 안기부 해외팀 차장 박평호와 국내팀 차장 김정도는 동림으로 알려진 안기부 내 스파이, 남파간첩 총책임자를 밝혀내는 임무를 맡는다. 이윽고 동림이 국가 안보를 위태롭게 할 1급 비밀 정보를 누설하기 시작하고 안기부의 해외팀과 국내팀은 서로를 조사하기에 이른다. 당장 스파이를 밝혀내지 못하면 자신이 혐의를 받을 수 있는 일촉즉발의 상황에서 평호와 정도는 서서히 진실을 찾아내고, 마침내 대한민국 1호 암살 작전이라는 거대한 사건과 직면하게 되는데...",
      popularity: 26.646,
      poster_path: "/zI0rMYcSUx16pHnsegWExPf1kDF.jpg",
      release_date: "2022-08-10",
      title: "헌트",
      video: false,
      vote_average: 8.5,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: "/7DBdVT5KEhjnMLpoejbYylfzd92.jpg",
      genre_ids: [16, 28, 80, 9648],
      id: 903939,
      original_language: "ja",
      original_title: "名探偵コナン ハロウィンの花嫁",
      overview:
        "극악무도한 폭파범 플라먀에 의해 교묘한 함정에 빠진 아무로 토오루! 모든 것이 베일에 가려진 플라먀, 유일한 단서는 아무로 토오루가 그의 경찰 동기들과 마지막으로 함께 했던 하루. 이와 동시에 결혼식의 신부가 된 경시청의 사토 형사는 불길한 예감을 감출 수 없는데…",
      popularity: 23.954,
      poster_path: "/8H1jQGdc2tC5f3BAdaiERQrhPOW.jpg",
      release_date: "2022-07-13",
      title: "명탐정 코난: 할로윈의 신부",
      video: false,
      vote_average: 5.7,
      vote_count: 16,
    },
    {
      adult: false,
      backdrop_path: "/2PUM5pDpAzF9fsmmkNH9jBbj1yt.jpg",
      genre_ids: [18, 53, 80, 9648],
      id: 10851,
      original_language: "en",
      original_title: "Revolver",
      overview:
        "불법 도박의 누명을 쓰고  7년 동안 독방에서 출소의 그날 만을 기다리며  치밀한 복수의 계획을 세운 '제이크 그린'(제이슨 스타뎀)  그를 감옥으로 보낸 '도로시'(레이 리오타) 역시  '제이크'의 석방만을 기다리며 기회를 노리고 있었다.  하지만 서로를 잡기 위해  치열한 사투를 벌이는 그들 앞에는  예상치 못한 대반전이 기다리고 있는데…",
      popularity: 22.823,
      poster_path: "/5gNViECeK0b1VuyB7a0ZTdtwRnC.jpg",
      release_date: "2022-08-11",
      title: "리볼버",
      video: false,
      vote_average: 6.4,
      vote_count: 1090,
    },
    {
      adult: false,
      backdrop_path: "/zXEiUyCOC8DOQ20CoEmRCaA5pa3.jpg",
      genre_ids: [18, 53],
      id: 626872,
      original_language: "ko",
      original_title: "비상선언",
      overview:
        "베테랑 형사 팀장 인호는 비행기 테러 예고 영상 제보를 받고 사건을 수사하던 중 용의자가 실제로 KI501 항공편에 타고 있음을 파악한다.딸의 치료를 위해 비행 공포증임에도 불구하고 하와이로 떠나기로 한 재혁은 주변을 맴돌며 위협적인 말을 하는 낯선 이가 신경 쓰인다.인천에서 하와이로 이륙한 KI501 항공편에서 원인불명의 사망자가 나오고, 비행기 안은 물론 지상까지 혼란과 두려움의 현장으로 뒤바뀐다.이 소식을 들은 국토부 장관 숙희는 대테러센터를 구성하고 비행기를 착륙시킬 방법을 찾기 위해 긴급회의를 소집하는데…",
      popularity: 22.435,
      poster_path: "/h8gyJKvIHzXo5HrGOe2WOJEe0IV.jpg",
      release_date: "2022-08-03",
      title: "비상선언",
      video: false,
      vote_average: 7.5,
      vote_count: 7,
    },
  ],
  total_pages: 3,
  total_results: 54,
};
